<?php

class Generic_CustomField_Def {

	const DT_FORMAT_YMD = 'yy-mm-dd';

	// definitions for: Custom Field Group

	static function required() {
		return array(
			array(
				'group_name' => 'Customers_Data',
				'group_title' => 'Customer Data',
				'extends' => array('Organization'),
				'entities' => array(
					'Customer',
				),
				'style' => 'Tab',
				'is_multiple' => FALSE,
				'help_pre' => '<p>Used for Webform: New Customer.</p>
',
				'help_post' => '',
				'collapse_display' => 0,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Employee_Information',
				'group_title' => 'Yearly Information',
				'extends' => array('Organization'),
				'entities' => array(
					'Customer',
				),
				'style' => 'Tab',
				'is_multiple' => TRUE,
				'help_pre' => '',
				'help_post' => '',
				'collapse_display' => 0,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Additional_Data',
				'group_title' => 'Additional Data',
				'extends' => array('Individual'),
				'entities' => array(
					NULL,
				),
				'style' => 'Inline',
				'is_multiple' => FALSE,
				'help_pre' => 'Additional data required by PUM',
				'help_post' => '',
				'collapse_display' => 0,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Projectinformation',
				'group_title' => 'Projectinformation',
				'extends' => array('Case'),
				'entities' => array(
					'Projectintake',
				),
				'style' => 'Inline',
				'is_multiple' => FALSE,
				'help_pre' => '',
				'help_post' => '',
				'collapse_display' => 1,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Passport_Information',
				'group_title' => 'Passport Information',
				'extends' => array('Individual'),
				'entities' => array(
					NULL,
				),
				'style' => 'Inline',
				'is_multiple' => FALSE,
				'help_pre' => '',
				'help_post' => '',
				'collapse_display' => 0,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Languages',
				'group_title' => 'Languages',
				'extends' => array('Individual'),
				'entities' => array(
					'Expert',
				),
				'style' => 'Tab',
				'is_multiple' => TRUE,
				'help_pre' => '',
				'help_post' => '',
				'collapse_display' => 0,
				'collapse_adv_display' => 1,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Interview_Information',
				'group_title' => 'RCT Intake Report',
				'extends' => array('Case'),
				'entities' => array(
					'Expertapplication',
				),
				'style' => 'Inline',
				'is_multiple' => FALSE,
				'help_pre' => '<p>Used to add RCT Assessment.</p>',
				'help_post' => '',
				'collapse_display' => 1,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Assessment_Expert_Application',
				'group_title' => 'Rejection Application New Expert',
				'extends' => array('Case'),
				'entities' => array(
					'Expertapplication',
				),
				'style' => 'Inline',
				'is_multiple' => FALSE,
				'help_pre' => '',
				'help_post' => '',
				'collapse_display' => 1,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Work_Experience',
				'group_title' => 'Work Experience',
				'extends' => array('Relationship'),
				'entities' => array(
					'Employer of',
				),
				'style' => 'Inline',
				'is_multiple' => FALSE,
				'help_pre' => '',
				'help_post' => '',
				'collapse_display' => 0,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Medical_Information',
				'group_title' => 'Medical Information',
				'extends' => array('Individual'),
				'entities' => array(
					'Expert',
				),
				'style' => 'Inline',
				'is_multiple' => FALSE,
				'help_pre' => '',
				'help_post' => '',
				'collapse_display' => 0,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Bank_Information',
				'group_title' => 'Bank Information',
				'extends' => array('Individual'),
				'entities' => array(
					NULL,
				),
				'style' => 'Inline',
				'is_multiple' => FALSE,
				'help_pre' => '',
				'help_post' => '',
				'collapse_display' => 0,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Expert_Data',
				'group_title' => 'Expert Data',
				'extends' => array('Individual'),
				'entities' => array(
					'Expert',
				),
				'style' => 'Tab',
				'is_multiple' => FALSE,
				'help_pre' => '<p>Data specific to the role PUM Expert</p>
',
				'help_post' => '',
				'collapse_display' => 0,
				'collapse_adv_display' => 1,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Education',
				'group_title' => 'Education',
				'extends' => array('Individual'),
				'entities' => array(
					'Expert',
				),
				'style' => 'Tab',
				'is_multiple' => TRUE,
				'help_pre' => '<p>Used on the webform \"Expert PUM CV\" where Candidate Experts can fill out their relevant Education and training details</p>
',
				'help_post' => '',
				'collapse_display' => 1,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Intake_Customer_by_CC',
				'group_title' => 'Intake Customer by CC',
				'extends' => array('Activity'),
				'entities' => array(
					'Intake Customer by CC',
				),
				'style' => 'Inline',
				'is_multiple' => FALSE,
				'help_pre' => '<p>Used in &quot;Projectintake&quot;</p>',
				'help_post' => '',
				'collapse_display' => 0,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Intake_Customer_by_SC',
				'group_title' => 'Intake Customer by SC',
				'extends' => array('Activity'),
				'entities' => array(
					'Intake Customer by SC',
				),
				'style' => 'Inline',
				'is_multiple' => FALSE,
				'help_pre' => '<p>Used in &quot;Projectintake&quot;</p>',
				'help_post' => '',
				'collapse_display' => 1,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
			array(
				'group_name' => 'Intake_Customer_by_Anamon',
				'group_title' => 'Intake Customer by Anamon',
				'extends' => array('Activity'),
				'entities' => array(
					'Intake Customer by Anamon',
				),
				'style' => 'Inline',
				'is_multiple' => FALSE,
				'help_pre' => '<p>Used in &quot;projectintake&quot;</p>',
				'help_post' => '',
				'collapse_display' => 0,
				'collapse_adv_display' => 0,
				'fieldset' => array(
					array(
						'name' => 'civicrm_country_id',
						'label' => 'CountryID',
						'data_type' => 'String',
						'html_type' => 'Text',
						'default_value' => NULL,
						'is_required' => FALSE,
						'is_searchable' => FALSE,
						'is_search_range' => FALSE,
						'weight' => 10,
						'help_pre' => NULL,
						'help_post' => NULL,
						'attributes' => NULL,
						'options_per_line' => NULL,
						'text_length' => 25,
						'start_date_years' => NULL,
						'end_date_years' => NULL,
						'date_format' => self::DT_FORMAT_YMD,
						'time_format' => NULL,
						'note_columns' => 60,
						'note_rows' => 4,
						'option_group_name' => NULL,
					),
				),
			),
		);
	}
}
