<?php

class Generic_RelationshipType_Def {

	// definitions for: Relationship Type

	static function required() {
		return array(
			array(
				'module' => 'nl.pum.generic',
				'name' => 'Anamon',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'Anamon',
					'name_b_a' => 'Anamon',
					'label_a_b' => 'Anamon',
					'label_b_a' => 'Anamon',
					'contact_type_a' => '',
					'contact_sub_type_a' => '',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => 'Anamon relationship',
					'is_active' => 1,
				),
			),
			array(
				'module' => 'nl.pum.generic',
				'name' => 'Country Coordinator is',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'Country Coordinator is',
					'name_b_a' => 'Country Coordinator for',
					'label_a_b' => 'Country Coordinator is',
					'label_b_a' => 'Country Coordinator for',
					'contact_type_a' => 'Organization',
					'contact_sub_type_a' => '',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => 'Country Coordinator relationship',
					'is_active' => 1,
				),
			),
			array(
				'module' => 'nl.pum.generic',
				'name' => 'CV Intake',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'CV Intake',
					'name_b_a' => 'CV Intake',
					'label_a_b' => 'CV Intake',
					'label_b_a' => 'CV Intake',
					'contact_type_a' => 'Individual',
					'contact_sub_type_a' => 'Expert',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => 'CT Intake tbv Expertapplication',
					'is_active' => 1,
				),
			),
			array(
				'module' => 'nl.pum.generic',
				'name' => 'Expert',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'Expert',
					'name_b_a' => 'Expert',
					'label_a_b' => 'Expert',
					'label_b_a' => 'Expert',
					'contact_type_a' => '',
					'contact_sub_type_a' => '',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => 'Used for the relationship between sector and Active Expert',
					'is_active' => 1,
				),
			),
			array(
				'module' => 'nl.pum.generic',
				'name' => 'Has authorised',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'Has authorised',
					'name_b_a' => 'Authorised contact for',
					'label_a_b' => 'Has authorised',
					'label_b_a' => 'Authorised contact for',
					'contact_type_a' => 'Organization',
					'contact_sub_type_a' => '',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => 'Customer contact relationship',
					'is_active' => 1,
				),
			),
			array(
				'module' => 'nl.pum.generic',
				'name' => 'Head Personnel and Organisation',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'Head Personnel and Organisation',
					'name_b_a' => 'Head Personnel and Organisation',
					'label_a_b' => 'Head Personnel and Organisation',
					'label_b_a' => 'Head Personnel and Organisation',
					'contact_type_a' => 'Individual',
					'contact_sub_type_a' => 'Expert',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => 'Head Personnel and Organisation',
					'is_active' => 1,
				),
			),
			array(
				'module' => 'nl.pum.generic',
				'name' => 'ICE (In Case of Emergency) call',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'ICE (In Case of Emergency) call',
					'name_b_a' => 'ICE (In Case of Emergency) for',
					'label_a_b' => 'ICE (In Case of Emergency) call',
					'label_b_a' => 'ICE (In Case of Emergency) for',
					'contact_type_a' => 'Individual',
					'contact_sub_type_a' => 'Expert',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => '',
					'is_active' => 1,
				),
			),
			array(
				'module' => 'nl.pum.generic',
				'name' => 'Project Officer',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'Project Officer for',
					'name_b_a' => 'Project Officer is',
					'label_a_b' => 'Project Officer',
					'label_b_a' => 'Project Officer',
					'contact_type_a' => '',
					'contact_sub_type_a' => '',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => 'Project Officer relationship',
					'is_active' => 1,
				),
			),
			array(
				'module' => 'nl.pum.generic',
				'name' => 'Projectmanager',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'Projectmanager',
					'name_b_a' => 'Projectmanager',
					'label_a_b' => 'Projectmanager',
					'label_b_a' => 'Projectmanager',
					'contact_type_a' => 'Organization',
					'contact_sub_type_a' => '',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => 'Projectmanager relationship',
					'is_active' => 1,
				),
			),
			array(
				'module' => 'nl.pum.generic',
				'name' => 'Recruitment Team Member',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'Recruitment Team Member',
					'name_b_a' => 'Recruitment Team Member',
					'label_a_b' => 'Recruitment Team Member',
					'label_b_a' => 'Recruitment Team Member',
					'contact_type_a' => 'Individual',
					'contact_sub_type_a' => 'Expert',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => 'Recruitment Team Member',
					'is_active' => 1,
				),
			),
			array(
				'module' => 'nl.pum.generic',
				'name' => 'Representative is',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'Representative is',
					'name_b_a' => 'Representative for',
					'label_a_b' => 'Representative is',
					'label_b_a' => 'Representative for',
					'contact_type_a' => 'Organization',
					'contact_sub_type_a' => '',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => 'PUM representative relationship',
					'is_active' => 1,
				),
			),
			array(
				'module' => 'nl.pum.generic',
				'name' => 'Sector Coordinator',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'Sector Coordinator',
					'name_b_a' => 'Sector Coordinator',
					'label_a_b' => 'Sector Coordinator',
					'label_b_a' => 'Sector Coordinator',
					'contact_type_a' => '',
					'contact_sub_type_a' => '',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => 'Sector Coordinator relationship',
					'is_active' => 1,
				),
			),
			array(
				'module' => 'nl.pum.generic',
				'name' => 'Sector Support Officer',
				'entity' => 'RelationshipType',
				'params' => array(
					'version' => 3,
					'name_a_b' => 'Sector Support Officer',
					'name_b_a' => 'Sector Support Officer',
					'label_a_b' => 'Sector Support Officer',
					'label_b_a' => 'Sector Support Officer',
					'contact_type_a' => 'Individual',
					'contact_sub_type_a' => 'Expert',
					'contact_type_b' => 'Individual',
					'contact_sub_type_b' => '',
					'description' => 'Sector Support Officer',
					'is_active' => 1,
				),
			),
		);
	}
}
